version: 0.2
phases:
  build:
    commands:
    - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_Linux.tar.gz
        tar -xvf ZAP_2.13.0_Linux.tar.gz
        cd ZAP_2.13.0
        ./zap.sh -cmd -quickurl http://zero.webappsecurity.com/ -quickprogress -quickout ../zap_report.html 
artifacts:
  files:
    - zap_report.html
